### ISSUE TITLE
TinyMCE preview missing for short codes

### ISSUE THREAD

**Issue by knowtheory** [documentcloud/wordpress-documentcloud#40] opened 2016-03-13 23:21 UTC
If you paste `http://www.documentcloud.org/documents/282753-lefler-thesis.html` into the TinyMCE editor and then flip to visual mode, the document will be loaded via oembed.

If you paste in `[documentcloud url="http://www.documentcloud.org/documents/282753-lefler-thesis.html" width=100 height=100 sidebar=false]` (to shut off the sidebar) and then flip to the visual mode, the shortcode is not converted to an embed in editor.

**Comment by reefdog** [comment] 2016-03-16 16:16
I know TinyMCE powers the post-editing interface, but as that's an implementation detail, should probably just reference "Text" and "Visual" modes for clarity.

**Comment by eyeseast** [comment] 2016-03-18 16:15
I think this can get lumped into #25, if we use Shortcake. I keep meaning to get to that but keep getting sidetracked by work projects (and the sick).

**Comment by reefdog** [comment] 2016-03-18 16:19
Is it related? I'm genuinely unsure. What Ted's describing: if you flip to text mode of a post and paste in a raw DC URL (like https://www.documentcloud.org/documents/282753-lefler-thesis.html) and then flip to Visual mode, the embed gets fetched and inserted into the post body. Which is super cool. But if you flip to text mode and paste in a shortcode, then flip back to visual mode, the shortcode is *not* converted to an embed.

Wait, actually. I think this might be expected behavior. A URL can't be configured, so it makes sense to just convert it straight to an embed even in visual mode. But a shortcode can be configured, so it would be super annoying for it to convert to an embed in visual mode.

@knowtheory I think we can wontfix this.

**Comment by reefdog** [comment] 2016-03-18 16:21
In fact definitely.

**Closed by reefdog** 2016-03-18 16:21 UTC
Labels: bug

**Comment by knowtheory** [comment] 2016-03-18 16:25
wait, wat?

Why is this #wontfix?  You should still be able to configure in text mode right?  The Q is where the preview happens and whether you can get that in the editor or whether you have to hit the preview button right?

**Comment by knowtheory** [comment] 2016-03-18 16:27
It is super weird to me that the straight URL embeds but not the shortcode, but if that's expected behavior... i guess that's okay?

**Comment by reefdog** [comment] 2016-03-18 16:31
It's the intersection of a few things that make it reasonable.

Straight URLs don't carry any embed configuration options, so it's a straight functionality gain to have them convert to an actual embed in Visual mode. Shortcodes carry configuration options, so having *them* convert to an embed would means the user would have to flip to Text mode to configure it. Since most users live in Visual mode, WP leaves those alone. If you want to preview shortcodes, you have to use the normal Preview functionality.
